version: '3.7'

service:

  mysql:
    image: mysql:5.7.30
    container_name: database
    restart: always
    
    ports:
      - 3306:3306
    networks:
      - aplicacao
    volumes:
      - mysql:/var/lib/mysql
      
    environment:
      - MTSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
        
  api:
    container_name: api
    restart: on-failure
    networks:
      - aplicacao
    depends_on:
      - mysql
    
    build:
      context: .
    volumes:
      - .:/var/www/html
      
    ports:
      - 8080:80
    env_file:
      - .env
      
networks:
  aplicacao:

volumes:
  mysql:
